### ISSUE TITLE
Script ./copy-pet-clinic.sh is not found (repository cannot be created)

### ISSUE THREAD

**Issue by Bart09876** [dxc-technology/about-devops-dojo#62]
**Describe the bug**
I'm trying to setup my environment "Setup the Pet-Clinic repository" I've created the GitHub account and token, but when I try to run command: ./copy-pet-clinic.sh it gives me error that file is not found.

Yes, I checked the FAQ: https://dxc-technology.github.io/about-devops-dojo/get-help/

**To Reproduce**
1. Go to terminal and trigger command: ./copy-pet-clinic.sh
2. Error is returned - file not found

**Expected behavior**
Script is triggered and repository created.

**Screenshots**

![image](https://user-images.githubusercontent.com/74907506/99957939-c2af4280-2d88-11eb-97ba-8ad549ce8854.png)

**Additional context**

**Comment by pberthonneau** [comment]
Hi Bart, thanks.
We are working on it. There was a regression on Katacoda platform and several of our environments are impacted.
We will update you once the environment is back.

**Comment by Bart09876** [comment]
Ok, thanks!

**Comment by pberthonneau** [comment]
Hi  @Bart09876 , Katacoda is back!

Enjoy the Dojo and do not hesitate to give your feedbacks🎉
