### ISSUE TITLE
Step 3 Generate Token - did that but says step not complete

### ISSUE THREAD

**Issue by BobS337** [dxc-technology/about-devops-dojo#66]
**Please describe your question, with as much details as possible**
A clear and concise description of what the question is.

**Comment by BobS337** [comment]
during step 3 of setup, I created a GitHub account and logged in and created the token; when I clicked Continue but I got the errror: you must complete this step when I did?  What am I missing?

**Comment by BobS337** [comment]
I am unable to continue to step 4 of SETUP???

**Comment by tom-halpin** [comment]
@BobS337 thank you for your interest in the Dojo.

I presume you are referring to Step 3 of the Welcome module, 

Please ensure the token was created with repo and admin:repo scopes 

if that doesn't work please forward the detailed error message you receive

**Comment by BobS337** [comment]
Tom,

Here is my token:  793b9ee22dc50fb03212140ec1c2831efa1b41d3 

Here is the error message from step 3 of 4 on Copy the Pet Clinic application:  "Please complete the task before proceeding"

When I created this account in GitHub it was created in a different window if that matters?

Thanks,

Bob

**Comment by tom-halpin** [comment]
@BobS337 did you hit return after entering the token in the terminal window ? before pressing the continue button in the instruction window?

Also just as an FYI, and as you are probably aware to protect the integrity of your account, now that you have shared it above,  I strongly recommend you delete that token and try again with a new one.

**Comment by BobS337** [comment]
Thanks Tom!

I created a new token.

Started over and got back to step 3

Entered the token into the command line and hit enter and got the command line error: "Command not Found"

Sorry...haven't used a CLI for a long time...

Please help...Thanks!

Bob 
Bob Skertic 
Professor and Learning Director (LD) for Information Technology (IT)
Production, Coordination & Optimization (PCO)
Defense Acquisition University 
Bob.Skertic@dau.edu
Office: (703) 805-5281     DSN: 655 
FAX: (703) 805-5082 
"God grant that men of principle shall be our principal men." - Thomas Jefferson
Play Hard, Play Smart, Have Fun! 
You MUST Sacrifice to SUCCEED! 
Attitude = Everything = Effort = Success! 
"Never sacrifice INTEGRITY for success"
If you judge people, you have no time to love them.
Kind words can be short and easy to speak, but their echoes are truly endless.


-----Original Message-----

**Comment by BobS337** [comment]
Tom…

Got it to work…

Sorry about this…

Recommend reminding folks to do the

./copy-pet-clinic.sh <return>

Then COPY TEXT token into space hit return

Thanks!

Bob
Bob Skertic
Professor and Learning Director (LD) for Information Technology (IT)
Production, Coordination & Optimization (PCO)
Defense Acquisition University
Bob.Skertic@dau.edu
Office: (703) 805-5281     DSN: 655
FAX: (703) 805-5082
"God grant that men of principle shall be our principal men." - Thomas Jefferson
Play Hard, Play Smart, Have Fun!
You MUST Sacrifice to SUCCEED!
Attitude = Everything = Effort = Success!
"Never sacrifice INTEGRITY for success"
If you judge people, you have no time to love them.
Kind words can be short and easy to speak, but their echoes are truly endless.

**Comment by tom-halpin** [comment]
@BobS337 ahah I think I know what the issue is

you need to run the command ./copy-pet-clinic.sh as shown below

![image](https://user-images.githubusercontent.com/20931122/104075772-c0575980-520b-11eb-8da0-35f780173bd0.png)

you can do this by clicking on the command or entering it directly from the keyboard

then once prompted enter the token

**Comment by BobS337** [comment]
Tom,

I had followed your  example exactly but it took me so long to create an account the command line interface forgot or I hit something by accident…then, after I finally created a new GitHub account (Tried for an hour to revive my old GitHub where I forgot my password AND I changed phones without saving the TOTP Auth recovery codes into the cloud) that I finally gave up and established a new account using my work userid…

So…that’s why it didn’t work…had you put an example at the bottom of step three I would have not have gotten any error…

Thanks!

Bob
Bob Skertic
Professor and Learning Director (LD) for Information Technology (IT)
Production, Coordination & Optimization (PCO)
Defense Acquisition University
Bob.Skertic@dau.edu
Office: (703) 805-5281     DSN: 655
FAX: (703) 805-5082
"God grant that men of principle shall be our principal men." - Thomas Jefferson
Play Hard, Play Smart, Have Fun!
You MUST Sacrifice to SUCCEED!
Attitude = Everything = Effort = Success!
"Never sacrifice INTEGRITY for success"
If you judge people, you have no time to love them.
Kind words can be short and easy to speak, but their echoes are truly endless.

From: Skertic, Robert
Sent: Friday, January 8, 2021 6:45 PM
To: 'dxc-technology/about-devops-dojo' <reply@reply.github.com>; dxc-technology/about-devops-dojo <about-devops-dojo@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [External Sender] Re: [dxc-technology/about-devops-dojo] Step 3 Generate Token - did that but says step not complete (#66)

Tom…

Got it to work…

Sorry about this…

Recommend reminding folks to do the

./copy-pet-clinic.sh <return>

Then COPY TEXT token into space hit return

Thanks!

Bob
Bob Skertic
Professor and Learning Director (LD) for Information Technology (IT)
Production, Coordination & Optimization (PCO)
Defense Acquisition University
Bob.Skertic@dau.edu
Office: (703) 805-5281     DSN: 655
FAX: (703) 805-5082
"God grant that men of principle shall be our principal men." - Thomas Jefferson
Play Hard, Play Smart, Have Fun!
You MUST Sacrifice to SUCCEED!
Attitude = Everything = Effort = Success!
"Never sacrifice INTEGRITY for success"
If you judge people, you have no time to love them.
Kind words can be short and easy to speak, but their echoes are truly endless.

**Comment by tom-halpin** [comment]
Great, enjoy the dojo @BobS337

**Comment by BobS337** [comment]
Tom,

Recommend in Step 4, you change the last "install" to "save" to be consistent with GitHub app...I am good to go.

Thanks so much for your help...Have a Great Weekend!

Bob

Bob 
Bob Skertic 
Professor and Learning Director (LD) for Information Technology (IT)
Production, Coordination & Optimization (PCO)
Defense Acquisition University 
Bob.Skertic@dau.edu
Office: (703) 805-5281     DSN: 655 
FAX: (703) 805-5082 
"God grant that men of principle shall be our principal men." - Thomas Jefferson
Play Hard, Play Smart, Have Fun! 
You MUST Sacrifice to SUCCEED! 
Attitude = Everything = Effort = Success! 
"Never sacrifice INTEGRITY for success"
If you judge people, you have no time to love them.
Kind words can be short and easy to speak, but their echoes are truly endless.


-----Original Message-----
