### ISSUE TITLE
2 modules are no longer available

### ISSUE THREAD

**Issue by chiaki-h** [dxc-technology/about-devops-dojo#72]
Hi,

It seems like 2 modules on Online DevOps Dojo are not available. Other modules are working. Would you please look at what is wrong with those 2 modules?

Here are the screenshots:
- Continuous Integration
![スクリーンショット 2022-03-18 114604](https://user-images.githubusercontent.com/101623780/158928078-2f6dab42-4ddb-49bc-961d-5ced00a6f931.png)

- Shift left on Security
![スクリーンショット 2022-03-18 114734](https://user-images.githubusercontent.com/101623780/158928055-75818df8-1ca5-4c87-976f-fd8ee9305719.png)

Thank you in advance.

**Comment by bn-stephen** [comment]
still not working as of today

**Comment by pberthonneau** [comment]
Hello

Katacoda (Oreilly) has definitely stopped to sell its license. Normally no module should work anymore.
But they didn't properly decommission their infrastructure then it might work by chance for some modules.
We would like to migrate to another platform but do not have the cycles at the moment.

Philippe for DXC

**Comment by chiaki-h** [comment]
Thank you @pberthonneau for your reply.
I understand the situation now. 

Chiaki from DXC Japan
